<?php

/**
 * @author Antony Gitonga
 * This is the new site ":any" driver
 * 
 */

class App extends CI_Controller {
    
    function _construct ()
    {
        parent::__construct();
        
    }
    
    function index ()
    {
        /**
         * This determines what to load
         * We can load, @var Product Single Product
         *              @var Category Product Category view
         *              @var Auto Generated page BAckdoor autogenerated page
         */
        
        //Start with pdoduct listing
        $link = $this->uri->segment(1);
        if($this->slug ($link)):
            
        elseif($this->category($link)):
            
        elseif($this->auto_gen ($link)):
            
        else:
            $this->FourOhFour ($link);
        endif;
    }
    
    function slug ($link)
    {
        $this->db->where('slug', $link);
        $data = $this->db->get('item');
        
        if($data->num_rows () !== 1):
            return false;
        else:
            $this->render($data);
            return true;
        endif;
        
    }
    
    function category($link)
    {
        $this->db->where('cat_slug', $link);
        $data = $this->db->get('categories');
        
        
        if($data -> num_rows () != 1):
            return false;
        else:
            $this->cat_render($data);
        endif;
    }
        
    function auto_gen ($link)
    {
        return true;
    }
    
    function cat_render ($data)
    {
        foreach ($data -> result () as $write):
            $cat_id = $write->cat_id;
            $info['cat'] = $write;
            $info['main'] = 'cat_view';
            $info['title'] = $write->cat_name;
            $info['rt'] = $this->data->get_cat_data($cat_id);
            $info['keywords'] = $write->cat_desc;
            $info['description'] = $write->cat_desc;

            $this->load->view('loader', $info);
        endforeach;
    }
    
    
            
    
    function render ($data)
    {
        foreach ($data -> result () as $write):
        //$lat = $write->lat;
        //$long = $write->long;
        $info['row'] = $write;
        
       // echo '<pre>';
       // print_r($write);
        //$info['map'] = $this->data-> map_single ($lat, $long);

        $info['main'] = 'view';
        $info['title'] = $write->name;
        $info['single'] = $this->data->get_single_ft();
        $info['keywords'] = $write->name . ' for hire in ' . $write->region;
        $info['description'] = word_limiter($write->desc, 12);

        $this->load->view('loader', $info);
        endforeach;
    }
    
    
    
}

?>
